/*
 * Ski Data API for NEU Seattle distributed systems course
 * An API for an emulation of skier managment system for RFID tagged lift tickets. Basis for CS6650 Assignments for 2019
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import io.swagger.client.ApiException;
import io.swagger.client.api.StatisticsApi;
import io.swagger.client.model.APIStats;
import org.junit.Ignore;
import org.junit.Test;


/**
 * API tests for StatisticsApi
 */
@Ignore
public class StatisticsApiTest {

    private final StatisticsApi api = new StatisticsApi();

    /**
     * get the API performance stats
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getPerformanceStatsTest() throws Exception {

        try {
            APIStats response = api.getPerformanceStats();
        } catch (ApiException e) {
            System.err.println("Exception when calling ResortsApi#addSeason");
            e.printStackTrace();
        }
        // TODO: test validations
    }
}
